### ISSUE TITLE
Removed App from Google Play Store

### ISSUE THREAD

**Issue by IstrateAndrei** [ThePerfectApp/TPA-SDK-Android#1]
I've published an app on Google Play store and it got removed because it was using a content provider with an insecure implementation of openFile. 

google support link: https://support.google.com/faqs/answer/7496913?hl=en

The thing is that I'm not using any Content Providers inside my application and can't do much about it.

The only vulnerable category found by google is: io.tpa.tpalib.distribution.FileProvider

If anyone can bring some insight on how to solve this, would be great.

**Comment by kringelbach** [comment]
Hi Andrei,

We already discussed this on the support-email, so I am just adding the reply here for reference 😊

The Distribution lib is not intended for Google Play Store use. It is used to update test apps installed from TPA. When you ship your app to Google Play, you should not include the lib, but instead users should update apps directly using Google Play Store.
